services:
  backend1:
    image: ghcr.io/frenzywall/metrics_pythonslim:latest
    container_name: backend1
    environment:
      - INSTANCE_ID=1
      - TZ=Asia/Kolkata
    networks:
      - app-network
    volumes:
      - shared:/confs

  backend2:
    image: ghcr.io/frenzywall/metrics_pythonslim:latest
    container_name: backend2
    environment:
      - INSTANCE_ID=2
      - TZ=Asia/Kolkata
    networks:
      - app-network

  backend3:
    image: ghcr.io/frenzywall/metrics_pythonslim:latest
    container_name: backend3
    environment:
      - INSTANCE_ID=3
      - TZ=Asia/Kolkata
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - shared:/etc/nginx/
    networks:
      - app-network
    environment:
      - TZ=Asia/Kolkata
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  shared: